### ISSUE TITLE
Markdown Tables Rendered Incorrectly

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [googlecodelabs/tools#526]
```
| foo  | bar |
|------|-----|
| val1 | val2 |
```
I'd expect to be rendered as:

| foo  | bar |
|------|-----|
| val1 | val2 |

But it actually comes out missing the header as:

![image](https://user-images.githubusercontent.com/13639658/99764165-30b8f700-2b48-11eb-8dd7-7e49eca9b40e.png)

**Comment by Pflanzgurke** [comment]
Hi, are you using the latest version of the tools? That used to be a bug, but was fixed here:

https://github.com/googlecodelabs/tools/issues/399

or you just found a regression...

**Comment by poppy191** [comment]
I don't understand what you say.my rnglish is very poor•2020年11月20日 16:44，Rolf Winter <notifications@github.com>寫道：
Hi, are you using the latest version of the tools? That used to be a bug, but was fixed here:
#399
or you just found a regression...

**Comment by Dynatrace-Adam-Gardner** [comment]
Hi @Pflanzgurke `claat version` prints a blank line and the releases page doesn't contain the claat binary that I could see.

I have just re-ran `go get github.com/googlecodelabs/tools/claat` as per the [readme](https://github.com/googlecodelabs/tools/blob/master/claat/README.md) and it's still broken. Line endings are shown as I've found it doesn't like windows line endings:

![image](https://user-images.githubusercontent.com/13639658/100079692-b1e9f400-2e90-11eb-9c39-9fa2a11a56f6.png)

**Comment by Dynatrace-Adam-Gardner** [comment]
Yes. It's a regression. From the markdown you posted on #399 

![image](https://user-images.githubusercontent.com/13639658/100080107-2886f180-2e91-11eb-8118-e2f17028e964.png)

**Comment by caramelmelmel** [comment]
It has been fixed! Updated your claat version again
